// PURPOSE: test array out-of-bounds exceptions.

var failed = false;

failed = false;
try { var x = [1 2 3 4]; system.println("${x[4]}"); } catch (error e) { failed = true; }
assert(failed);


failed = false;
try { var x = [[1 2] [3 4]]; system.println("${x[1,2]}"); } catch (error e) { failed = true; }
assert(failed);

